# Generated by Django 3.1.5 on 2021-01-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100)),
                ('ip_type', models.CharField(max_length=10)),
                ('continent_code', models.CharField(max_length=100)),
                ('continent_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('region_code', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.TextField(default='')),
                ('time_zone', models.TextField(default='')),
                ('currency', models.TextField(default='')),
                ('connection', models.TextField(default='')),
            ],
        ),
    ]
