# Generated by Django 3.1.5 on 2021-01-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='connection',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='currency',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='time_zone',
            field=models.TextField(default=''),
        ),
    ]
