# Generated by Django 3.1.5 on 2021-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0002_auto_20210107_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='calling_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='capital',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='country_flag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='country_flag_emoji',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='country_flag_emoji_unicode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='geoname_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='is_eu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='language_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='language_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='native_language_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
